name: wandb_env
channels:
  - conda-forge
dependencies:
  - python=3.9  # Or your preferred Python version
  - pip
  - wandb
  - pip:
    - numpy  # While not explicitly imported, it's a common dependency for numerical tasks
